services:
  rstudio:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: fluidos_corte_r

    working_dir: /workspace

    volumes:
      - .:/workspace

    environment:
      TZ: America/Sao_Paulo
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

    stdin_open: true
    tty: true

    command: bash